services:
  postgres:
    image: postgres:17
    container_name: amazon_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123} 
      POSTGRES_DB: ${POSTGRES_DB:-amazon_db} 
    ports:
      - "5433:5432"
    volumes:
      - ./data/clean:/data/origin:ro
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d amazon_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - review-analysis-network

volumes:
  postgres_data:

networks:
  review-analysis-network:
    external: true